import type { Metadata } from "next";
import { Amethysta } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "@/app/components/ReactQueryClientProvider";
import { ReactNode } from "react";
import {
  Button,
  Footer,
  FooterBrand,
  FooterLink,
  FooterLinkGroup,
  FooterTitle,
  Navbar,
  NavbarBrand,
  NavbarCollapse,
  NavbarToggle,
} from "flowbite-react";
import Link from "next/link";
import Image from "next/image";
import Navlink from "@/app/components/Navlink";

const inter = Amethysta({ weight: "400", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="fr">
        <body className={inter.className}>
          <div className="bg-black border-b border-brown">
            <Navbar fluid className="bg-black max-w-screen-lg mx-auto">
              <div className={"flex items-center gap-8"}>
                <NavbarBrand as={Link} href="/">
                  <div className={"relative mr-3 h-full aspect-square sm:h-9"}>
                    <Image
                      src="/wineLogo.png"
                      alt="Wine logo"
                      fill
                      className=""
                    />
                  </div>
                  <span className="self-center whitespace-nowrap text-xl text-brown font-semibold dark:text-white">
                    Et Si Le Vin ?
                  </span>
                </NavbarBrand>
                <NavbarCollapse className="!text-brown">
                  <Navlink href="/">Accueil</Navlink>
                  <Navlink href="/workshop">Ateliers</Navlink>
                  <Navlink href="/about">A propos</Navlink>
                </NavbarCollapse>
              </div>
              <div className="flex">
                <Link
                  href={"/workshop"}
                  className="px-4 py-2 bg-brown rounded-none text-white"
                >
                  Participer à un atelier
                </Link>
                <NavbarToggle />
              </div>
            </Navbar>
          </div>
          <>{children}</>
          <Footer
            container
            className="border-t border-t-brown rounded-none bg-black pt-12"
          >
            <div className="w-3/6 flex flex-col items-center">
              <FooterBrand
                href="/"
                src="/wineLogo.png"
                alt="Wine logo"
                className="flex flex-col "
              />
              <span className="text-white whitespace-nowrap text-2xl font-semibold">
                Et Si Le Vin ?
              </span>
            </div>
            <div className="flex justify-start items-start w-3/6">
              <FooterLinkGroup col className="text-white mr-60">
                <FooterTitle title="Pages" className="text-white" />
                <FooterLink href="/">Accueil</FooterLink>
                <FooterLink href="/workshop">Atelier</FooterLink>
                <FooterLink href="/about">A propos</FooterLink>
                <FooterLink href="/login">Connexion</FooterLink>
              </FooterLinkGroup>
              <FooterLinkGroup col className="text-white">
                <FooterTitle title="Mention légale" className="text-white" />
                <FooterLink href="#">Conditions générales</FooterLink>
                <FooterLink href="#">Politique de confidentialité</FooterLink>
                <FooterLink href="#">Paramètres des cookies</FooterLink>
              </FooterLinkGroup>
            </div>
          </Footer>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
